# Generated by Django 3.1.3 on 2022-03-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashBook1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency_symbol',
            field=models.TextField(max_length=100),
        ),
    ]
