# Generated by Django 3.1.3 on 2022-03-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashBook1', '0002_auto_20220320_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(max_length=100),
        ),
    ]
