# Generated by Django 3.1.3 on 2022-03-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashBook1', '0003_auto_20220320_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
