# Generated by Django 3.1.3 on 2022-03-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashBook1', '0005_goal_goal_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='create_date',
        ),
    ]
