# Generated by Django 3.1.3 on 2022-03-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashBook1', '0006_remove_goal_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goal_Data',
            new_name='GoalData',
        ),
    ]
