# Generated by Django 3.1.3 on 2022-06-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashBook1', '0009_auto_20220323_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goaldata',
            name='goal_id',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='GoalData',
        ),
    ]
